/* Automatically generated by p4c-ebpf from pkt-filter.p4 on Thu Apr 22 00:02:39 2021
 */
#ifndef _P4_GEN_HEADER_
#define _P4_GEN_HEADER_
#include "ebpf_kernel.h"

#define MAP_PATH "/sys/fs/bpf/tc/globals"
struct ethernet_t {
    u64 dstAddr; /* macAddr_t */
    u64 srcAddr; /* macAddr_t */
    u16 etherType; /* bit<16> */
    u8 ebpf_valid;
};

struct ipv4_t {
    u8 version; /* bit<4> */
    u8 ihl; /* bit<4> */
    u8 diffserv; /* bit<8> */
    u16 totalLen; /* bit<16> */
    u16 id; /* bit<16> */
    u8 flags; /* bit<3> */
    u16 fragOffset; /* bit<13> */
    u8 ttl; /* bit<8> */
    u8 protocol; /* bit<8> */
    u16 hdrChecksum; /* bit<16> */
    u32 srcAddr; /* ip4Addr_t */
    u32 dstAddr; /* ip4Addr_t */
    u8 ebpf_valid;
};

struct udp_t {
    u16 sport; /* bit<16> */
    u16 dport; /* bit<16> */
    u16 len; /* bit<16> */
    u16 checksum; /* bit<16> */
    u8 ebpf_valid;
};

struct metadata {
    u32 counter; /* bit<32> */
};

struct headers {
    struct ethernet_t ethernet; /* ethernet_t */
    struct ipv4_t ipv4; /* ipv4_t */
    struct udp_t udp; /* udp_t */
};

struct MyFilter_udp_exact_key {
    u16 field0; /* hdr.udp.dport */
};
enum udp_exact_0_actions {
    MyFilter_drop,
    MyFilter_save,
};
struct MyFilter_udp_exact_value {
    enum udp_exact_0_actions action;
    union {
        struct {
        } MyFilter_drop;
        struct {
        } MyFilter_save;
    } u;
};
typedef u32 MyFilter_drop_save_counter_key;
typedef u32 MyFilter_drop_save_counter_value;
#if CONTROL_PLANE
static void init_tables() 
{
    u32 ebpf_zero = 0;
    {
        int tableFileDescriptor = BPF_OBJ_GET(MAP_PATH "/MyFilter_udp_exact_defaultAction");
        if (tableFileDescriptor < 0) { fprintf(stderr, "map MyFilter_udp_exact_defaultAction not loaded\n"); exit(1); }
        struct MyFilter_udp_exact_value value = {
            .action = MyFilter_drop,
            .u = {.MyFilter_drop = {}},
        };
        int ok = BPF_USER_MAP_UPDATE_ELEM(tableFileDescriptor, &ebpf_zero, &value, BPF_ANY);
        if (ok != 0) { perror("Could not write in MyFilter_udp_exact_defaultAction"); exit(1); }
    }
}
#endif
#endif
